USE_CASES = {
    "Use case 1": {
        "name": "DuneAI",
        "description": "Lung Cancer medical algorithm evaluation supporting EHR and imaging data",
        "implemented": True,
        "data_type": "images",
        "expected_columns": [
            "PatientID",
            "age",
            "clinical.T.Stage",
            "Clinical.N.Stage",
            "Clinical.M.Stage",
            "Overall.Stage",
            "Histology",
            "gender",
            "Survival.time",
            "deadstatus.event",
        ],
        "column_types": {
            "PatientID": "categorical",
            "age": "numeric",
            "clinical.T.Stage": "categorical",
            "Clinical.N.Stage": "categorical",
            "Clinical.M.Stage": "categorical",
            "Overall.Stage": "categorical",
            "Histology": "categorical",
            "gender": "categorical",
            "Survival.time": "numeric",
            "deadstatus.event": "categorical",
        },
        "expected_ranges": {
            "age": [0, 120],
            "clinical.T.Stage": [1, 5],
            "Clinical.N.Stage": [0, 4],
            "Clinical.M.Stage": [0, 3],
            "Survival.time": [0, 10000],
        },
        "target_column": "deadstatus.event",
        "image_quality_checks": {
            "population_representativity": {
                "description": "Minority/majority class ratio from histology distribution or patient image count balance",
                "method": "minority_majority_ratio_analysis",
                "sdqf_rating": "≤0.2 ratio = 1/5, ≥0.8 ratio = 5/5",
            },
            "metadata_granularity": {
                "description": "Patients with complete metadata / total patients ratio",
                "method": "metadata_coverage_ratio_analysis",
                "sdqf_rating": "≤0.2 ratio = 1/5, ≥0.8 ratio = 5/5",
            },
            "accuracy": {
                "description": "CT-scan slice dimension consistency and missing slice detection",
                "method": "slice_consistency_and_completeness_analysis",
                "sdqf_rating": "≤0.2 error ratio = 5/5, ≥0.8 error ratio = 1/5",
            },
            "coherence": {
                "description": "Consistent number of channels across all images (grayscale vs RGB)",
                "method": "channel_consistency_analysis",
                "sdqf_rating": "≤0.2 inconsistency ratio = 5/5, ≥0.8 inconsistency ratio = 1/5",
            },
            "semantic_coherence": {
                "description": "Duplicate image detection using array hash comparison",
                "method": "image_duplicate_detection",
                "sdqf_rating": "≤0.2 duplication ratio = 5/5, ≥0.8 duplication ratio = 1/5",
            },
            "completeness": {
                "description": "Missing pixels / total pixels ratio across all images",
                "method": "pixel_completeness_analysis",
                "sdqf_rating": "≤0.2 missing ratio = 5/5, ≥0.8 missing ratio = 1/5",
            },
        },
        "clinical_metadata_file": "NSCLC-Radiomics-Lung1.clinical-version3-Oct-2019.csv",
        "image_extensions": [".nrrd", ".mha", ".nii", ".nii.gz"],
        "expected_patient_id_pattern": "LUNG1-\\d{3}",
    },
    "Use case 2": {
        "name": "PGx2P",
        "description": "Pharmacogenomics Passports to Practice",
        "implemented": True,
        "data_type": "tabular",
        "expected_columns": [
            "CHROM",
            "POS",
            "ID",
            "REF",
            "ALT",
            "QUAL",
            "FILTER",
            "INFO",
            "FORMAT",
        ],
        "column_types": {
            "CHROM": "categorical",
            "POS": "numeric",
            "ID": "categorical",
            "REF": "categorical",
            "ALT": "categorical",
            "QUAL": "numeric",
            "FILTER": "categorical",
            "INFO": "categorical",
            "FORMAT": "categorical",
        },
        "expected_ranges": {
            "CHROM": [
                "chr1",
                "chr2",
                "chr3",
                "chr4",
                "chr5",
                "chr6",
                "chr7",
                "chr8",
                "chr9",
                "chr10",
                "chr11",
                "chr12",
                "chr13",
                "chr14",
                "chr15",
                "chr16",
                "chr17",
                "chr18",
                "chr19",
                "chr20",
                "chr21",
                "chr22",
                "chrX",
                "chrY",
                "chrM",
            ],
        },
        "target_column": ["CYP2B6", "CYP2C9", "CYP2C19", "CYP3A5", "SLCO1B1", "TPMT"],
    },
    "Use case 3": {
        "name": "STAR",
        "description": "Glucose control in intensive care units",
        "implemented": True,
        "data_type": "time_series",
        "column_types": {
            "age": "numeric",
            "gender": "categorical",
            "diabeticStatus": "categorical",
            "weight": "numeric",
            "blood_glucose": "numeric",
            "insulin_infusion": "numeric",
            "enteral_nutrition": "numeric",
            "parenteral_nutrition": "numeric",
        },
        "expected_ranges": {
            "age": (0, 120),
            "gender": ["Male", "Female"],
            "diabeticStatus": [0, 1, 2],
            "weight": (0, 300),
        },
    },
    "Use case 4": {
        "name": "ASCOPD",
        "description": "Medical AI models for COPD and ASTHMA inpatient risk stratification",
        "implemented": True,
        "data_type": "tabular",
        "expected_columns": [
            "age",
            "Sex",
            "Hemoglobin",
            "Platelet Count",
            "Urea Nitrogen",
            "Creatinine",
            "Sodium",
            "Potassium",
            "ALT",
            "Glucose",
            "PH",
            "pO2",
            "pCO2",
            "Bicarbonate",
            "Absolute Neutrophil Count",
            "Absolute Monocyte Count",
            "Eosinophils",
            "Absolute Lymphocyte Count",
        ],
        "column_types": {
            "age": "numeric",
            "Sex": "categorical",
            "Hemoglobin": "numeric",
            "Platelet Count": "numeric",
            "Urea Nitrogen": "numeric",
            "Creatinine": "numeric",
            "Sodium": "numeric",
            "Potassium": "numeric",
            "ALT": "numeric",
            "Glucose": "numeric",
            "PH": "numeric",
            "pO2": "numeric",
            "pCO2": "numeric",
            "Bicarbonate": "numeric",
            "Absolute Neutrophil Count": "numeric",
            "Absolute Monocyte Count": "numeric",
            "Eosinophils": "numeric",
            "Absolute Lymphocyte Count": "numeric",
        },
        "expected_ranges": {
            "age": [0, 120],
            "Sex": [0, 1],
            "PH": [0, 14],
        },
        "target_column": ["ARF", "Mortality", "VenDep"],
    },
    "Use case 5": {
        "name": "COPowereD",
        "description": "Medical AI algorithms using patient reported outcomes for COPD to detect and predict hospitalization or acute exacerbations",
        "implemented": False,
        "data_type": "tabular",
    },
}
